name: Build and Publish Gem

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

# Grant necessary permissions for the workflow
permissions:
  contents: write    # Required to create tags and releases
  packages: write    # Required for package publishing
  actions: read      # Required to read workflow

jobs:
  build-and-publish:
    # Only run this job if the TEST workflow was successful and on main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        
    - name: Get current version
      id: version
      run: |
        TARGET_VERSION=$(ruby -r './lib/vagrant_ssh_config_manager/version.rb' -e 'puts VagrantPlugins::SshConfigManager::VERSION')
        echo "Using current version: $TARGET_VERSION"
        echo "target_version=$TARGET_VERSION" >> $GITHUB_OUTPUT
        echo "TARGET_VERSION=$TARGET_VERSION" >> $GITHUB_ENV
        
    - name: Check if version already exists
      id: check_existing
      run: |
        # Check if git tag exists
        if git rev-parse "v${{ steps.version.outputs.target_version }}" >/dev/null 2>&1; then
          echo "git_tag_exists=true" >> $GITHUB_OUTPUT
        else
          echo "git_tag_exists=false" >> $GITHUB_OUTPUT
        fi
        
        # Check if gem exists on RubyGems
        if gem list -r vagrant-ssh-config-manager | grep -q "${{ steps.version.outputs.target_version }}"; then
          echo "gem_exists=true" >> $GITHUB_OUTPUT
        else
          echo "gem_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create git tag
      if: steps.check_existing.outputs.git_tag_exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.version.outputs.target_version }}" -m "Release version ${{ steps.version.outputs.target_version }}"
        git push origin "v${{ steps.version.outputs.target_version }}"
        
    - name: Build gem
      run: gem build vagrant-ssh-config-manager.gemspec
        
    - name: Publish to RubyGems
      if: steps.check_existing.outputs.gem_exists == 'false'
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p ~/.gem
        echo ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem push vagrant-ssh-config-manager-${{ steps.version.outputs.target_version }}.gem
        
    - name: Create GitHub Release
      if: steps.check_existing.outputs.gem_exists == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.target_version }}
        name: Release v${{ steps.version.outputs.target_version }}
        draft: false
        prerelease: false
        files: vagrant-ssh-config-manager-${{ steps.version.outputs.target_version }}.gem
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Skip publishing - already exists
      if: steps.check_existing.outputs.gem_exists == 'true'
      run: |
        echo "::notice::Gem version ${{ steps.version.outputs.target_version }} already exists on RubyGems. Skipping publication."
