name: Run Rubocop

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.rb'
      - 'Gemfile'
      - 'lib/**'
      - 'spec/**'
      - 'vagrant-ssh-config-manager.gemspec'
      - '.github/workflows/**'
      - '.github/.trigger'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.3']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        
    - name: Run RuboCop
      run: bundle exec rubocop --format github --format json --out lint-results/ruby-${{ matrix.ruby-version }}_rubocop.json

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: lint-results-ruby-${{ matrix.ruby-version }}
        path: lint-results/
        retention-days: 7
        if-no-files-found: error